const ActionTypes = {
  RECEIVE_POKEMONS: 'RECEIVE_POKEMONS',
  RECEIVE_POKEMONS_DETAIL: 'RECEIVE_POKEMONS_DETAIL',
  CLEAR_POKEMON_DETAIL: 'CLEAR_POKEMON_DETAIL',
  ADD_FAVORITE_POKEMON: 'ADD_FAVORITE_POKEMON',
};

export { ActionTypes };
